import React from 'react';
import Container from 'react-bootstrap/esm/Container';

const About = () => {
  return (
    <Container>
      <p className='pt-5'></p> {/* отступ контента из-за фиксированного navbar */}
      <h1 className='text-center pt-3'>About</h1>
      <p className='text-center text-primary fw-bold fs-5 p-3'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis dolor laborum quas odio alias, id consequatur neque voluptatum illo ex? Ex incidunt nam illo facere vero numquam in mollitia quia atque assumenda fugiat, ipsa quos unde doloribus quis voluptates asperiores nobis id magnam expedita temporibus voluptatibus quaerat minima. Porro laborum distinctio delectus sit non rerum laudantium quasi? Repudiandae dolore vitae facere perferendis nemo unde expedita? Repellat aliquid id reprehenderit! Eius quaerat nobis corporis incidunt magnam, mollitia accusamus quibusdam, ut atque voluptate, ipsum est voluptatibus soluta. Odit officiis, nam modi quisquam itaque porro deleniti voluptates necessitatibus possimus, nemo dolore nesciunt a.</p>
      <p className='text-center text-primary fw-bold fs-5 p-3'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis dolor laborum quas odio alias, id consequatur neque voluptatum illo ex? Ex incidunt nam illo facere vero numquam in mollitia quia atque assumenda fugiat, ipsa quos unde doloribus quis voluptates asperiores nobis id magnam expedita temporibus voluptatibus quaerat minima. Porro laborum distinctio delectus sit non rerum laudantium quasi? Repudiandae dolore vitae facere perferendis nemo unde expedita? Repellat aliquid id reprehenderit! Eius quaerat nobis corporis incidunt magnam, mollitia accusamus quibusdam, ut atque voluptate, ipsum est voluptatibus soluta. Odit officiis, nam modi quisquam itaque porro deleniti voluptates necessitatibus possimus, nemo dolore nesciunt a.</p>
      <p className='text-center text-primary fw-bold fs-5 p-3'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis dolor laborum quas odio alias, id consequatur neque voluptatum illo ex? Ex incidunt nam illo facere vero numquam in mollitia quia atque assumenda fugiat, ipsa quos unde doloribus quis voluptates asperiores nobis id magnam expedita temporibus voluptatibus quaerat minima. Porro laborum distinctio delectus sit non rerum laudantium quasi? Repudiandae dolore vitae facere perferendis nemo unde expedita? Repellat aliquid id reprehenderit! Eius quaerat nobis corporis incidunt magnam, mollitia accusamus quibusdam, ut atque voluptate, ipsum est voluptatibus soluta. Odit officiis, nam modi quisquam itaque porro deleniti voluptates necessitatibus possimus, nemo dolore nesciunt a.</p>
      <p className='text-center text-primary fw-bold fs-5 p-3'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis dolor laborum quas odio alias, id consequatur neque voluptatum illo ex? Ex incidunt nam illo facere vero numquam in mollitia quia atque assumenda fugiat, ipsa quos unde doloribus quis voluptates asperiores nobis id magnam expedita temporibus voluptatibus quaerat minima. Porro laborum distinctio delectus sit non rerum laudantium quasi? Repudiandae dolore vitae facere perferendis nemo unde expedita? Repellat aliquid id reprehenderit! Eius quaerat nobis corporis incidunt magnam, mollitia accusamus quibusdam, ut atque voluptate, ipsum est voluptatibus soluta. Odit officiis, nam modi quisquam itaque porro deleniti voluptates necessitatibus possimus, nemo dolore nesciunt a.</p>
    </Container>
  )
}

export default About