import React from 'react'
import Container from 'react-bootstrap/esm/Container';

const Home = () => {
  return (
    <Container>
      <p className='pt-5'></p> {/* отступ контента из-за фиксированного navbar */}
      <h1 className='text-center pt-3'>Home</h1>
      <p className='text-center text-warning fw-bold fs-5 p-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptate ut dicta magnam enim porro eius dolorem? Perferendis tempora molestias reprehenderit tempore enim? Pariatur ullam est facilis reprehenderit perspiciatis id quaerat nisi in, sunt tenetur asperiores voluptatem sequi esse perferendis aperiam a et cumque? Eveniet cumque tempore modi ab nisi perferendis. Nulla corrupti suscipit asperiores porro nostrum voluptates blanditiis ipsam reiciendis fuga nesciunt provident architecto illo qui facere excepturi eaque vero magnam commodi, doloremque officiis sunt perferendis esse aliquid? Earum ipsa rem neque est numquam repudiandae non quibusdam at, laboriosam eius illo saepe eveniet nemo aut maiores voluptates quisquam! Quos.</p>
      <p className='text-center text-warning fw-bold fs-5 p-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptate ut dicta magnam enim porro eius dolorem? Perferendis tempora molestias reprehenderit tempore enim? Pariatur ullam est facilis reprehenderit perspiciatis id quaerat nisi in, sunt tenetur asperiores voluptatem sequi esse perferendis aperiam a et cumque? Eveniet cumque tempore modi ab nisi perferendis. Nulla corrupti suscipit asperiores porro nostrum voluptates blanditiis ipsam reiciendis fuga nesciunt provident architecto illo qui facere excepturi eaque vero magnam commodi, doloremque officiis sunt perferendis esse aliquid? Earum ipsa rem neque est numquam repudiandae non quibusdam at, laboriosam eius illo saepe eveniet nemo aut maiores voluptates quisquam! Quos.</p>
      <p className='text-center text-warning fw-bold fs-5 p-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptate ut dicta magnam enim porro eius dolorem? Perferendis tempora molestias reprehenderit tempore enim? Pariatur ullam est facilis reprehenderit perspiciatis id quaerat nisi in, sunt tenetur asperiores voluptatem sequi esse perferendis aperiam a et cumque? Eveniet cumque tempore modi ab nisi perferendis. Nulla corrupti suscipit asperiores porro nostrum voluptates blanditiis ipsam reiciendis fuga nesciunt provident architecto illo qui facere excepturi eaque vero magnam commodi, doloremque officiis sunt perferendis esse aliquid? Earum ipsa rem neque est numquam repudiandae non quibusdam at, laboriosam eius illo saepe eveniet nemo aut maiores voluptates quisquam! Quos.</p>
      <p className='text-center text-warning fw-bold fs-5 p-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptate ut dicta magnam enim porro eius dolorem? Perferendis tempora molestias reprehenderit tempore enim? Pariatur ullam est facilis reprehenderit perspiciatis id quaerat nisi in, sunt tenetur asperiores voluptatem sequi esse perferendis aperiam a et cumque? Eveniet cumque tempore modi ab nisi perferendis. Nulla corrupti suscipit asperiores porro nostrum voluptates blanditiis ipsam reiciendis fuga nesciunt provident architecto illo qui facere excepturi eaque vero magnam commodi, doloremque officiis sunt perferendis esse aliquid? Earum ipsa rem neque est numquam repudiandae non quibusdam at, laboriosam eius illo saepe eveniet nemo aut maiores voluptates quisquam! Quos.</p>
      <p className='text-center text-warning fw-bold fs-5 p-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptate ut dicta magnam enim porro eius dolorem? Perferendis tempora molestias reprehenderit tempore enim? Pariatur ullam est facilis reprehenderit perspiciatis id quaerat nisi in, sunt tenetur asperiores voluptatem sequi esse perferendis aperiam a et cumque? Eveniet cumque tempore modi ab nisi perferendis. Nulla corrupti suscipit asperiores porro nostrum voluptates blanditiis ipsam reiciendis fuga nesciunt provident architecto illo qui facere excepturi eaque vero magnam commodi, doloremque officiis sunt perferendis esse aliquid? Earum ipsa rem neque est numquam repudiandae non quibusdam at, laboriosam eius illo saepe eveniet nemo aut maiores voluptates quisquam! Quos.</p>
    </Container>
    
  )
}

export default Home;